import { refreshResearch } from "../researchService";
import { refreshAllWatchlistChannels } from "../watchlistService";
import { insertSocialChatMessage, getAllUserSettings } from "../db";
import { runAllStoresCycle, enrichPendingMarketChanges } from "../marketIntelService";

// Scheduler in-process (il server Railway è always-on): job giornalieri a orario
// fisso italiano, indipendenti dai bottoni della UI e dal browser aperto.
//   08:45 → refresh Watchlist (canali competitor)
//   09:00 → refresh Research Hub (fonti + punteggi AI + autopilot)
// L'orario si ricalcola ogni giorno dal fuso Europe/Rome (DST-safe).
const OWNER_USER_ID = 1;
const TIMEZONE = "Europe/Rome";

function secondsIntoRomeDay(): number {
  const parts = new Intl.DateTimeFormat("en-GB", {
    timeZone: TIMEZONE, hour: "2-digit", minute: "2-digit", second: "2-digit", hour12: false,
  }).formatToParts(new Date());
  const get = (type: string) => Number(parts.find((p) => p.type === type)?.value ?? 0);
  return (get("hour") % 24) * 3600 + get("minute") * 60 + get("second");
}

function msUntilNext(hour: number, minute: number): number {
  const target = hour * 3600 + minute * 60;
  let delta = target - secondsIntoRomeDay();
  if (delta <= 30) delta += 86_400; // già passato (o troppo vicino): domani
  return delta * 1000;
}

function scheduleDaily(hour: number, minute: number, name: string, fn: () => Promise<void>) {
  const arm = () => {
    const delay = msUntilNext(hour, minute);
    console.log(`[Scheduler] "${name}" tra ${Math.round(delay / 60000)} min (ogni giorno ${String(hour).padStart(2, "0")}:${String(minute).padStart(2, "0")} ${TIMEZONE})`);
    const timer = setTimeout(async () => {
      try {
        await fn();
      } catch (err) {
        console.warn(`[Scheduler] "${name}" fallito:`, err);
      }
      arm(); // riprogramma il giorno dopo
    }, delay);
    timer.unref?.(); // non tenere vivo il processo solo per il timer
  };
  arm();
}

// Fallback quando il server non ha un motore AI sincrono: il MOTORE PRIMARIO è
// l'agente VPS (abbonamento Claude). Se l'agente è online ma con codice pre-v5
// (senza research_loop), gli si chiede il lavoro via chat bridge.
const AGENT_ENRICH_TASK = `[SEO → ENRICH] Task automatico giornaliero del Research Hub.
Esegui in bash (il secret è già nel tuo ambiente, altrimenti: source ~/.social-agent.env):
1) curl -s -H "x-care-secret: $CARE_WEBHOOK_SECRET" "$SOCIAL_BASE_URL/api/seo/research/pending-enrich"
2) Per ogni item valuta CONTRO il brand_context ricevuto: targetScore 0-10, interestScore 0-10, brief (1-2 frasi it), angle (chiave di lettura brand), commentAnalysis+engagement per i reddit se leggibili dall'url (.rss).
3) POST il JSON {"items":[...]} a "$SOCIAL_BASE_URL/api/seo/research/enrichment" con lo stesso header.
Rispondi in chat solo con: quanti item hai analizzato.`;

export function registerDailySchedules() {
  if (!process.env.DATABASE_URL) {
    console.log("[Scheduler] DATABASE_URL assente — scheduler spento (dev locale)");
    return;
  }

  scheduleDaily(8, 45, "watchlist-refresh", async () => {
    const r = await refreshAllWatchlistChannels(OWNER_USER_ID);
    console.log(`[Scheduler] watchlist: ${r.refreshed} canali aggiornati, ${r.errors.length} errori`);
  });

  scheduleDaily(9, 0, "research-refresh", async () => {
    const r = await refreshResearch(OWNER_USER_ID);
    console.log(`[Scheduler] research 09:00: fetched=${r.fetched} stored=${r.stored} enriched=${r.enriched} autopilot=${r.autoGenerated} errori=${r.errors.length}`);
    // niente motore sincrono e niente research_loop attivo? chiedi all'agente via chat
    if (r.enriched === 0 && r.errors.some((e) => /Nessun motore AI/i.test(e))) {
      const s = await getAllUserSettings(OWNER_USER_ID);
      const lastSeen = Number(s.social_local_agent_last_seen ?? 0);
      if (lastSeen > 0 && Date.now() - lastSeen < 300_000) {
        await insertSocialChatMessage({
          userId: OWNER_USER_ID, role: "user", text: AGENT_ENRICH_TASK, status: "new", source: "web",
        }).catch((err) => console.warn("[Scheduler] handoff chat fallito:", err));
        console.log("[Scheduler] nessun motore sul server: enrichment delegato all'agente via chat bridge");
      }
    }
  });

  scheduleDaily(9, 15, "market-monitor", async () => {
    const r = await runAllStoresCycle(OWNER_USER_ID);
    console.log(`[Scheduler] market 09:15: stores=${r.stores} changes=${r.changes} errori=${r.errors.length}`);
    try { await enrichPendingMarketChanges(OWNER_USER_ID); } catch (e) { console.warn("[Scheduler] market enrich fallito:", e); }
  });
}
